### ISSUE TITLE
How to setup this, Where should i put the files?? Can you make the readme more readable to newbies??

### ISSUE THREAD

**Issue by n0yal** [wdomitrz/kitty-gruvbox-theme#1]

**Comment by wdomitrz** [comment]
Following <https://sw.kovidgoyal.net/kitty/conf.html>, add
```
include <path_to_theme_file>
```
in your kitty config file (on linux and mac os, it is most likely `~/.config/kitty/kitty.conf` -- if it does not exist, then just create it with that single line).

**Comment by wdomitrz** [comment]
@3301n Please let me know if it worked.
