### ISSUE TITLE
Relative dir for sub-include doesn't work

### ISSUE THREAD

**Issue by bitwombat** [wdomitrz/kitty-gruvbox-theme#3]
Thanks for making this!
If I have this line:
```
include /home/bitwombat/tmp/kitty-gruvbox-theme/gruvbox_light_hard.conf
```
I get this message:
```
Could not find included config file: /home/bitwombat/tmp/kitty-gruvbox-theme/./themes/gruvbox_light.conf
```
Doesn't seem to be the right path in the .conf file?

**Comment by wdomitrz** [comment]
Solved in https://github.com/wdomitrz/kitty-gruvbox-theme/pull/4, otherwise please reopen with more details to reproduce it.
